### ISSUE TITLE
Proposal - Using helm charts to manage k8s resources

### ISSUE THREAD

**Issue by gaubej** [gridsuite/deployment#108]
I'll like to introduce another way to deploy / design / customize k8s resources using helm.

Some advantages :

- Lifecycle management of k8s resources
- Personnalisation using command line or value file
- Distribution on public repository, so people can deploy without cloning this repository

I'll add an example in a PR.

Example of resources generation, from chart folder directly :

## Using all default value

`helm template gridsuite .`

## Disabling gridsuite component

`helm template gridsuite . --set gridstudy.enabled=false`

## Customizing image tag for gridmerge

`helm template gridsuite . --set gridmerge.image.tag="custoTag"`

### my_values.yaml :

```
gridstudy:
  ingress:
    annotations:
      monannotation: toto
      nginx.ingress.kubernetes.io/service-upstream: "false"
```
### CLI

`helm template gridsuite . -f ./my_values.yaml`
